<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search groups
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["groups/new", "Create groups"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "groups/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLable" class="col-sm-2 control-label">Lable</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["lable", "size" => 30, "class" => "form-control", "id" => "fieldLable"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreateAt" class="col-sm-2 control-label">Create</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(["create_at", [], "class" => "form-control", "id" => "fieldCreateAt"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
